version: '3.6'
services:

  redis:
    image: "redis:alpine"

  btg:
    build:
        dockerfile: Dockerfile
        context: .
    image: btg
    environment:
      - REDIS_HOST=redis
      - BTG_CONFIG=/btg.cfg
    depends_on:
      - redis
    links:
      - redis